/*
 Navicat Premium Data Transfer

 Source Server         : stkimain
 Source Server Type    : MySQL
 Source Server Version : 100414
 Source Host           : localhost:3306
 Source Schema         : stki

 Target Server Type    : MySQL
 Target Server Version : 100414
 File Encoding         : 65001

 Date: 14/10/2020 17:51:29
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for berita
-- ----------------------------
DROP TABLE IF EXISTS `berita`;
CREATE TABLE `berita`  (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `judul` tinytext CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `isi` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `url` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  INDEX `hasil`(`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 21 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of berita
-- ----------------------------
INSERT INTO `berita` VALUES (1, 'Pengeluaran BLT Dana Desa Masih di Bawah 50 persen', 'Jakarta, CNN Indonesia -- Menteri Koordinator Bidang Perekonomian Airlangga Hartarto menyampaikan penyaluran program bantuan langsung tunai (BLT) desa per 20 September 2020 sudah mencapai Rp15,1 triliun.\r\nRealisasi tersebut masih di bawah 50 persen dari total anggaran BLT Desa dalam program pemulihan ekonomi (PEN) yang mencapai Rp31,8 triliun.\r\n\"Ini berasal data dari Kementerian desa untuk 74.146,\" ujarnya dalam webinar yang digelar Kagama, Minggu (11/10).\r\n\r\n\r\n \r\nAirlangga melanjutkan, total dana itu telah tersalurkan kepada 7.970.652 kepala keluarga atau 72,45 persen dari total target 11 juta kepala keluarga di 74.146 desa yang jadi sasaran.\r\n\r\nIa melanjutkan, komposisi kelompok penerima manfaat BLT tersebut antara lain petani dan buruh tani sebesar 88 persen, nelayan dan buruh nelayan 4 persen, buruh pabrik sebesar 2 persen, guru 1 persen dan pedagang serta UMKM sebesar 5 persen.\r\n\r\n\"Kelompoknya adalah petani dan buruh tani sebesar 7 juta penerima, nelayan dan buruh nelayan 323.000, buruh pabrik sebesar 163.338, guru 68.780 dan pedagang serta UMKM 400.597,\" tuturnya.\r\nAirlangga melanjutkan, besaran BLT yang diberikan adalah Rp600 ribu per bulan untuk 3 bulan pertama. Setelah itu, tiga bulan berikutnya kelompok penerima manfaat akan diberikan BLT sebesar Rp300 ribu per bulan.\r\n\r\nPenerima manfaat sendiri berasal dari keluarga miskin atau tidak mampu dan tidak termasuk menerima program keluarga harapan, kartu sembako dan kartu prakerja.\r\n\r\n\"Pendataan penerima dilakukan oleh Kepala Desa atau tim relawan desa serta pendamping dari Pemda diatur oleh Kementerian Desa, Pembangunan Daerah Tertinggal dan Transmigrasi (KemendesPDTT),\" tandasnya.\r\n', 'https://www.cnnindonesia.com/ekonomi/20201011221231-78-557150/pengeluaran-blt-dana-desa-masih-di-bawah-50-persen');
INSERT INTO `berita` VALUES (2, '', '', '');
INSERT INTO `berita` VALUES (3, '', '', '');
INSERT INTO `berita` VALUES (4, '', '', '');
INSERT INTO `berita` VALUES (5, '', '', '');
INSERT INTO `berita` VALUES (6, '', '', '');
INSERT INTO `berita` VALUES (7, '', '', '');
INSERT INTO `berita` VALUES (8, '', '', '');
INSERT INTO `berita` VALUES (9, '', '', '');
INSERT INTO `berita` VALUES (10, '', '', '');
INSERT INTO `berita` VALUES (11, '', '', '');
INSERT INTO `berita` VALUES (12, '', '', '');
INSERT INTO `berita` VALUES (13, '', '', '');
INSERT INTO `berita` VALUES (14, '', '', '');
INSERT INTO `berita` VALUES (15, '', '', '');
INSERT INTO `berita` VALUES (16, '', '', '');
INSERT INTO `berita` VALUES (17, '', '', '');
INSERT INTO `berita` VALUES (18, '', '', '');
INSERT INTO `berita` VALUES (19, '', '', '');
INSERT INTO `berita` VALUES (20, '', '', '');

-- ----------------------------
-- Table structure for stopword
-- ----------------------------
DROP TABLE IF EXISTS `stopword`;
CREATE TABLE `stopword`  (
  `stopword` varchar(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL
) ENGINE = MyISAM CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of stopword
-- ----------------------------
INSERT INTO `stopword` VALUES ('ada');
INSERT INTO `stopword` VALUES ('adalah');
INSERT INTO `stopword` VALUES ('adanya');
INSERT INTO `stopword` VALUES ('adapun');
INSERT INTO `stopword` VALUES ('agak');
INSERT INTO `stopword` VALUES ('agaknya');
INSERT INTO `stopword` VALUES ('agar');
INSERT INTO `stopword` VALUES ('akan');
INSERT INTO `stopword` VALUES ('akankah');
INSERT INTO `stopword` VALUES ('akhir');
INSERT INTO `stopword` VALUES ('akhiri');
INSERT INTO `stopword` VALUES ('akhirnya');
INSERT INTO `stopword` VALUES ('aku');
INSERT INTO `stopword` VALUES ('akulah');
INSERT INTO `stopword` VALUES ('amat');
INSERT INTO `stopword` VALUES ('amatlah');
INSERT INTO `stopword` VALUES ('anda');
INSERT INTO `stopword` VALUES ('andalah');
INSERT INTO `stopword` VALUES ('antar');
INSERT INTO `stopword` VALUES ('antara');
INSERT INTO `stopword` VALUES ('antaranya');
INSERT INTO `stopword` VALUES ('apa');
INSERT INTO `stopword` VALUES ('apaan');
INSERT INTO `stopword` VALUES ('apabila');
INSERT INTO `stopword` VALUES ('apakah');
INSERT INTO `stopword` VALUES ('apalagi');
INSERT INTO `stopword` VALUES ('apatah');
INSERT INTO `stopword` VALUES ('artinya');
INSERT INTO `stopword` VALUES ('asal');
INSERT INTO `stopword` VALUES ('asalkan');
INSERT INTO `stopword` VALUES ('atas');
INSERT INTO `stopword` VALUES ('atau');
INSERT INTO `stopword` VALUES ('ataukah');
INSERT INTO `stopword` VALUES ('ataupun');
INSERT INTO `stopword` VALUES ('awal');
INSERT INTO `stopword` VALUES ('awalnya');
INSERT INTO `stopword` VALUES ('bagai');
INSERT INTO `stopword` VALUES ('bagaikan');
INSERT INTO `stopword` VALUES ('bagaimana');
INSERT INTO `stopword` VALUES ('bagaimanakah');
INSERT INTO `stopword` VALUES ('bagaimanapun');
INSERT INTO `stopword` VALUES ('bagi');
INSERT INTO `stopword` VALUES ('bagian');
INSERT INTO `stopword` VALUES ('bahkan');
INSERT INTO `stopword` VALUES ('bahwa');
INSERT INTO `stopword` VALUES ('bahwasanya');
INSERT INTO `stopword` VALUES ('baik');
INSERT INTO `stopword` VALUES ('baiknya');
INSERT INTO `stopword` VALUES ('bakal');
INSERT INTO `stopword` VALUES ('bakalan');
INSERT INTO `stopword` VALUES ('balik');
INSERT INTO `stopword` VALUES ('banyak');
INSERT INTO `stopword` VALUES ('bapak');
INSERT INTO `stopword` VALUES ('baru');
INSERT INTO `stopword` VALUES ('bawah');
INSERT INTO `stopword` VALUES ('beberapa');
INSERT INTO `stopword` VALUES ('begini');
INSERT INTO `stopword` VALUES ('beginian');
INSERT INTO `stopword` VALUES ('beginikah');
INSERT INTO `stopword` VALUES ('beginilah');
INSERT INTO `stopword` VALUES ('begitu');
INSERT INTO `stopword` VALUES ('begitukah');
INSERT INTO `stopword` VALUES ('begitulah');
INSERT INTO `stopword` VALUES ('begitupun');
INSERT INTO `stopword` VALUES ('bekerja');
INSERT INTO `stopword` VALUES ('belakang');
INSERT INTO `stopword` VALUES ('belakangan');
INSERT INTO `stopword` VALUES ('belum');
INSERT INTO `stopword` VALUES ('belumlah');
INSERT INTO `stopword` VALUES ('benar');
INSERT INTO `stopword` VALUES ('benarkah');
INSERT INTO `stopword` VALUES ('benarlah');
INSERT INTO `stopword` VALUES ('berada');
INSERT INTO `stopword` VALUES ('berakhir');
INSERT INTO `stopword` VALUES ('berakhirlah');
INSERT INTO `stopword` VALUES ('berakhirnya');
INSERT INTO `stopword` VALUES ('berapa');
INSERT INTO `stopword` VALUES ('berapakah');
INSERT INTO `stopword` VALUES ('berapalah');
INSERT INTO `stopword` VALUES ('berapapun');
INSERT INTO `stopword` VALUES ('berarti');
INSERT INTO `stopword` VALUES ('berawal');
INSERT INTO `stopword` VALUES ('berbagai');
INSERT INTO `stopword` VALUES ('berdatangan');
INSERT INTO `stopword` VALUES ('beri');
INSERT INTO `stopword` VALUES ('berikan');
INSERT INTO `stopword` VALUES ('berikut');
INSERT INTO `stopword` VALUES ('berikutnya');
INSERT INTO `stopword` VALUES ('berjumlah');
INSERT INTO `stopword` VALUES ('berkali');
INSERT INTO `stopword` VALUES ('berkata');
INSERT INTO `stopword` VALUES ('berkehendak');
INSERT INTO `stopword` VALUES ('berkeinginan');
INSERT INTO `stopword` VALUES ('berkenaan');
INSERT INTO `stopword` VALUES ('berlainan');
INSERT INTO `stopword` VALUES ('berlalu');
INSERT INTO `stopword` VALUES ('berlangsung');
INSERT INTO `stopword` VALUES ('berlebihan');
INSERT INTO `stopword` VALUES ('bermacam');
INSERT INTO `stopword` VALUES ('bermaksud');
INSERT INTO `stopword` VALUES ('bermula');
INSERT INTO `stopword` VALUES ('bersama');
INSERT INTO `stopword` VALUES ('bersiap');
INSERT INTO `stopword` VALUES ('bertanya');
INSERT INTO `stopword` VALUES ('berturut');
INSERT INTO `stopword` VALUES ('bertutur');
INSERT INTO `stopword` VALUES ('berujar');
INSERT INTO `stopword` VALUES ('berupa');
INSERT INTO `stopword` VALUES ('besar');
INSERT INTO `stopword` VALUES ('betul');
INSERT INTO `stopword` VALUES ('betulkah');
INSERT INTO `stopword` VALUES ('biasa');
INSERT INTO `stopword` VALUES ('biasanya');
INSERT INTO `stopword` VALUES ('bila');
INSERT INTO `stopword` VALUES ('bilakah');
INSERT INTO `stopword` VALUES ('bisa');
INSERT INTO `stopword` VALUES ('bisakah');
INSERT INTO `stopword` VALUES ('boleh');
INSERT INTO `stopword` VALUES ('bolehkah');
INSERT INTO `stopword` VALUES ('bolehlah');
INSERT INTO `stopword` VALUES ('buat');
INSERT INTO `stopword` VALUES ('bukan');
INSERT INTO `stopword` VALUES ('bukankah');
INSERT INTO `stopword` VALUES ('bukanlah');
INSERT INTO `stopword` VALUES ('bukannya');
INSERT INTO `stopword` VALUES ('bulan');
INSERT INTO `stopword` VALUES ('bung');
INSERT INTO `stopword` VALUES ('cara');
INSERT INTO `stopword` VALUES ('caranya');
INSERT INTO `stopword` VALUES ('cukup');
INSERT INTO `stopword` VALUES ('cukupkah');
INSERT INTO `stopword` VALUES ('cukuplah');
INSERT INTO `stopword` VALUES ('cuma');
INSERT INTO `stopword` VALUES ('dahulu');
INSERT INTO `stopword` VALUES ('dalam');
INSERT INTO `stopword` VALUES ('dan');
INSERT INTO `stopword` VALUES ('dapat');
INSERT INTO `stopword` VALUES ('dari');
INSERT INTO `stopword` VALUES ('daripada');
INSERT INTO `stopword` VALUES ('datang');
INSERT INTO `stopword` VALUES ('dekat');
INSERT INTO `stopword` VALUES ('demi');
INSERT INTO `stopword` VALUES ('demikian');
INSERT INTO `stopword` VALUES ('demikianlah');
INSERT INTO `stopword` VALUES ('dengan');
INSERT INTO `stopword` VALUES ('depan');
INSERT INTO `stopword` VALUES ('di');
INSERT INTO `stopword` VALUES ('dia');
INSERT INTO `stopword` VALUES ('diakhiri');
INSERT INTO `stopword` VALUES ('diakhirinya');
INSERT INTO `stopword` VALUES ('dialah');
INSERT INTO `stopword` VALUES ('diantara');
INSERT INTO `stopword` VALUES ('diantaranya');
INSERT INTO `stopword` VALUES ('diberi');
INSERT INTO `stopword` VALUES ('diberikan');
INSERT INTO `stopword` VALUES ('diberikannya');
INSERT INTO `stopword` VALUES ('dibuat');
INSERT INTO `stopword` VALUES ('dibuatnya');
INSERT INTO `stopword` VALUES ('didapat');
INSERT INTO `stopword` VALUES ('didatangkan');
INSERT INTO `stopword` VALUES ('digunakan');
INSERT INTO `stopword` VALUES ('diibaratkan');
INSERT INTO `stopword` VALUES ('diibaratkannya');
INSERT INTO `stopword` VALUES ('diingat');
INSERT INTO `stopword` VALUES ('diingatkan');
INSERT INTO `stopword` VALUES ('diinginkan');
INSERT INTO `stopword` VALUES ('dijawab');
INSERT INTO `stopword` VALUES ('dijelaskan');
INSERT INTO `stopword` VALUES ('dijelaskannya');
INSERT INTO `stopword` VALUES ('dikarenakan');
INSERT INTO `stopword` VALUES ('dikatakan');
INSERT INTO `stopword` VALUES ('dikatakannya');
INSERT INTO `stopword` VALUES ('dikerjakan');
INSERT INTO `stopword` VALUES ('diketahui');
INSERT INTO `stopword` VALUES ('diketahuinya');
INSERT INTO `stopword` VALUES ('dikira');
INSERT INTO `stopword` VALUES ('dilakukan');
INSERT INTO `stopword` VALUES ('dilalui');
INSERT INTO `stopword` VALUES ('dilihat');
INSERT INTO `stopword` VALUES ('dimaksud');
INSERT INTO `stopword` VALUES ('dimaksudkan');
INSERT INTO `stopword` VALUES ('dimaksudkannya');
INSERT INTO `stopword` VALUES ('dimaksudnya');
INSERT INTO `stopword` VALUES ('diminta');
INSERT INTO `stopword` VALUES ('dimintai');
INSERT INTO `stopword` VALUES ('dimisalkan');
INSERT INTO `stopword` VALUES ('dimulai');
INSERT INTO `stopword` VALUES ('dimulailah');
INSERT INTO `stopword` VALUES ('dimulainya');
INSERT INTO `stopword` VALUES ('dimungkinkan');
INSERT INTO `stopword` VALUES ('dini');
INSERT INTO `stopword` VALUES ('dipastikan');
INSERT INTO `stopword` VALUES ('diperbuat');
INSERT INTO `stopword` VALUES ('diperbuatnya');
INSERT INTO `stopword` VALUES ('dipergunakan');
INSERT INTO `stopword` VALUES ('diperkirakan');
INSERT INTO `stopword` VALUES ('diperlihatkan');
INSERT INTO `stopword` VALUES ('diperlukan');
INSERT INTO `stopword` VALUES ('diperlukannya');
INSERT INTO `stopword` VALUES ('dipersoalkan');
INSERT INTO `stopword` VALUES ('dipertanyakan');
INSERT INTO `stopword` VALUES ('dipunyai');
INSERT INTO `stopword` VALUES ('diri');
INSERT INTO `stopword` VALUES ('dirinya');
INSERT INTO `stopword` VALUES ('disampaikan');
INSERT INTO `stopword` VALUES ('disebut');
INSERT INTO `stopword` VALUES ('disebutkan');
INSERT INTO `stopword` VALUES ('disebutkannya');
INSERT INTO `stopword` VALUES ('disini');
INSERT INTO `stopword` VALUES ('disinilah');
INSERT INTO `stopword` VALUES ('ditambahkan');
INSERT INTO `stopword` VALUES ('ditandaskan');
INSERT INTO `stopword` VALUES ('ditanya');
INSERT INTO `stopword` VALUES ('ditanyai');
INSERT INTO `stopword` VALUES ('ditanyakan');
INSERT INTO `stopword` VALUES ('ditegaskan');
INSERT INTO `stopword` VALUES ('ditujukan');
INSERT INTO `stopword` VALUES ('ditunjuk');
INSERT INTO `stopword` VALUES ('ditunjuki');
INSERT INTO `stopword` VALUES ('ditunjukkan');
INSERT INTO `stopword` VALUES ('ditunjukkannya');
INSERT INTO `stopword` VALUES ('ditunjuknya');
INSERT INTO `stopword` VALUES ('dituturkan');
INSERT INTO `stopword` VALUES ('dituturkannya');
INSERT INTO `stopword` VALUES ('diucapkan');
INSERT INTO `stopword` VALUES ('diucapkannya');
INSERT INTO `stopword` VALUES ('diungkapkan');
INSERT INTO `stopword` VALUES ('dong');
INSERT INTO `stopword` VALUES ('dua');
INSERT INTO `stopword` VALUES ('dulu');
INSERT INTO `stopword` VALUES ('empat');
INSERT INTO `stopword` VALUES ('enggak');
INSERT INTO `stopword` VALUES ('enggaknya');
INSERT INTO `stopword` VALUES ('entah');
INSERT INTO `stopword` VALUES ('entahlah');
INSERT INTO `stopword` VALUES ('guna');
INSERT INTO `stopword` VALUES ('gunakan');
INSERT INTO `stopword` VALUES ('hal');
INSERT INTO `stopword` VALUES ('hampir');
INSERT INTO `stopword` VALUES ('hanya');
INSERT INTO `stopword` VALUES ('hanyalah');
INSERT INTO `stopword` VALUES ('hari');
INSERT INTO `stopword` VALUES ('harus');
INSERT INTO `stopword` VALUES ('haruslah');
INSERT INTO `stopword` VALUES ('harusnya');
INSERT INTO `stopword` VALUES ('hendak');
INSERT INTO `stopword` VALUES ('hendaklah');
INSERT INTO `stopword` VALUES ('hendaknya');
INSERT INTO `stopword` VALUES ('hingga');
INSERT INTO `stopword` VALUES ('ia');
INSERT INTO `stopword` VALUES ('ialah');
INSERT INTO `stopword` VALUES ('ibarat');
INSERT INTO `stopword` VALUES ('ibaratkan');
INSERT INTO `stopword` VALUES ('ibaratnya');
INSERT INTO `stopword` VALUES ('ibu');
INSERT INTO `stopword` VALUES ('ikut');
INSERT INTO `stopword` VALUES ('ingat');
INSERT INTO `stopword` VALUES ('ingin');
INSERT INTO `stopword` VALUES ('inginkah');
INSERT INTO `stopword` VALUES ('inginkan');
INSERT INTO `stopword` VALUES ('ini');
INSERT INTO `stopword` VALUES ('inikah');
INSERT INTO `stopword` VALUES ('inilah');
INSERT INTO `stopword` VALUES ('itu');
INSERT INTO `stopword` VALUES ('itukah');
INSERT INTO `stopword` VALUES ('itulah');
INSERT INTO `stopword` VALUES ('jadi');
INSERT INTO `stopword` VALUES ('jadilah');
INSERT INTO `stopword` VALUES ('jadinya');
INSERT INTO `stopword` VALUES ('jangan');
INSERT INTO `stopword` VALUES ('jangankan');
INSERT INTO `stopword` VALUES ('janganlah');
INSERT INTO `stopword` VALUES ('jauh');
INSERT INTO `stopword` VALUES ('jawab');
INSERT INTO `stopword` VALUES ('jawaban');
INSERT INTO `stopword` VALUES ('jawabnya');
INSERT INTO `stopword` VALUES ('jelas');
INSERT INTO `stopword` VALUES ('jelaskan');
INSERT INTO `stopword` VALUES ('jelaslah');
INSERT INTO `stopword` VALUES ('jelasnya');
INSERT INTO `stopword` VALUES ('jika');
INSERT INTO `stopword` VALUES ('jikalau');
INSERT INTO `stopword` VALUES ('juga');
INSERT INTO `stopword` VALUES ('jumlah');
INSERT INTO `stopword` VALUES ('jumlahnya');
INSERT INTO `stopword` VALUES ('justru');
INSERT INTO `stopword` VALUES ('kala');
INSERT INTO `stopword` VALUES ('kalau');
INSERT INTO `stopword` VALUES ('kalaulah');
INSERT INTO `stopword` VALUES ('kalaupun');
INSERT INTO `stopword` VALUES ('kali');
INSERT INTO `stopword` VALUES ('kalian');
INSERT INTO `stopword` VALUES ('kami');
INSERT INTO `stopword` VALUES ('kamilah');
INSERT INTO `stopword` VALUES ('kamu');
INSERT INTO `stopword` VALUES ('kamulah');
INSERT INTO `stopword` VALUES ('kan');
INSERT INTO `stopword` VALUES ('kapan');
INSERT INTO `stopword` VALUES ('kapankah');
INSERT INTO `stopword` VALUES ('kapanpun');
INSERT INTO `stopword` VALUES ('karena');
INSERT INTO `stopword` VALUES ('karenanya');
INSERT INTO `stopword` VALUES ('kasus');
INSERT INTO `stopword` VALUES ('kata');
INSERT INTO `stopword` VALUES ('katakan');
INSERT INTO `stopword` VALUES ('katakanlah');
INSERT INTO `stopword` VALUES ('katanya');
INSERT INTO `stopword` VALUES ('ke');
INSERT INTO `stopword` VALUES ('keadaan');
INSERT INTO `stopword` VALUES ('kebetulan');
INSERT INTO `stopword` VALUES ('kecil');
INSERT INTO `stopword` VALUES ('kedua');
INSERT INTO `stopword` VALUES ('keduanya');
INSERT INTO `stopword` VALUES ('keinginan');
INSERT INTO `stopword` VALUES ('kelamaan');
INSERT INTO `stopword` VALUES ('kelihatan');
INSERT INTO `stopword` VALUES ('kelihatannya');
INSERT INTO `stopword` VALUES ('kelima');
INSERT INTO `stopword` VALUES ('keluar');
INSERT INTO `stopword` VALUES ('kembali');
INSERT INTO `stopword` VALUES ('kemudian');
INSERT INTO `stopword` VALUES ('kemungkinan');
INSERT INTO `stopword` VALUES ('kemungkinannya');
INSERT INTO `stopword` VALUES ('kenapa');
INSERT INTO `stopword` VALUES ('kepada');
INSERT INTO `stopword` VALUES ('kepadanya');
INSERT INTO `stopword` VALUES ('kesampaian');
INSERT INTO `stopword` VALUES ('keseluruhan');
INSERT INTO `stopword` VALUES ('keseluruhannya');
INSERT INTO `stopword` VALUES ('keterlaluan');
INSERT INTO `stopword` VALUES ('ketika');
INSERT INTO `stopword` VALUES ('khususnya');
INSERT INTO `stopword` VALUES ('kini');
INSERT INTO `stopword` VALUES ('kinilah');
INSERT INTO `stopword` VALUES ('kira');
INSERT INTO `stopword` VALUES ('kiranya');
INSERT INTO `stopword` VALUES ('kita');
INSERT INTO `stopword` VALUES ('kitalah');
INSERT INTO `stopword` VALUES ('kok');
INSERT INTO `stopword` VALUES ('kurang');
INSERT INTO `stopword` VALUES ('kurangnya');
INSERT INTO `stopword` VALUES ('lagi');
INSERT INTO `stopword` VALUES ('lagian');
INSERT INTO `stopword` VALUES ('lah');
INSERT INTO `stopword` VALUES ('lain');
INSERT INTO `stopword` VALUES ('lainnya');
INSERT INTO `stopword` VALUES ('lalu');
INSERT INTO `stopword` VALUES ('lama');
INSERT INTO `stopword` VALUES ('lamanya');
INSERT INTO `stopword` VALUES ('lanjut');
INSERT INTO `stopword` VALUES ('lanjutnya');
INSERT INTO `stopword` VALUES ('lebih');
INSERT INTO `stopword` VALUES ('lewat');
INSERT INTO `stopword` VALUES ('lima');
INSERT INTO `stopword` VALUES ('luar');
INSERT INTO `stopword` VALUES ('macam');
INSERT INTO `stopword` VALUES ('maka');
INSERT INTO `stopword` VALUES ('makanya');
INSERT INTO `stopword` VALUES ('makin');
INSERT INTO `stopword` VALUES ('malah');
INSERT INTO `stopword` VALUES ('malahan');
INSERT INTO `stopword` VALUES ('mampu');
INSERT INTO `stopword` VALUES ('mampukah');
INSERT INTO `stopword` VALUES ('mana');
INSERT INTO `stopword` VALUES ('manakala');
INSERT INTO `stopword` VALUES ('manalagi');
INSERT INTO `stopword` VALUES ('masa');
INSERT INTO `stopword` VALUES ('masalah');
INSERT INTO `stopword` VALUES ('masalahnya');
INSERT INTO `stopword` VALUES ('masih');
INSERT INTO `stopword` VALUES ('masihkah');
INSERT INTO `stopword` VALUES ('masing');
INSERT INTO `stopword` VALUES ('mata');
INSERT INTO `stopword` VALUES ('mau');
INSERT INTO `stopword` VALUES ('maupun');
INSERT INTO `stopword` VALUES ('melainkan');
INSERT INTO `stopword` VALUES ('melakukan');
INSERT INTO `stopword` VALUES ('melalui');
INSERT INTO `stopword` VALUES ('melihat');
INSERT INTO `stopword` VALUES ('melihatnya');
INSERT INTO `stopword` VALUES ('memang');
INSERT INTO `stopword` VALUES ('memastikan');
INSERT INTO `stopword` VALUES ('memberi');
INSERT INTO `stopword` VALUES ('memberikan');
INSERT INTO `stopword` VALUES ('membuat');
INSERT INTO `stopword` VALUES ('memerlukan');
INSERT INTO `stopword` VALUES ('memihak');
INSERT INTO `stopword` VALUES ('meminta');
INSERT INTO `stopword` VALUES ('memintakan');
INSERT INTO `stopword` VALUES ('memisalkan');
INSERT INTO `stopword` VALUES ('memperbuat');
INSERT INTO `stopword` VALUES ('mempergunakan');
INSERT INTO `stopword` VALUES ('memperkirakan');
INSERT INTO `stopword` VALUES ('memperlihatkan');
INSERT INTO `stopword` VALUES ('mempersiapkan');
INSERT INTO `stopword` VALUES ('mempersoalkan');
INSERT INTO `stopword` VALUES ('mempertanyakan');
INSERT INTO `stopword` VALUES ('mempunyai');
INSERT INTO `stopword` VALUES ('memulai');
INSERT INTO `stopword` VALUES ('memungkinkan');
INSERT INTO `stopword` VALUES ('menaiki');
INSERT INTO `stopword` VALUES ('menambahkan');
INSERT INTO `stopword` VALUES ('menandaskan');
INSERT INTO `stopword` VALUES ('menanti');
INSERT INTO `stopword` VALUES ('menantikan');
INSERT INTO `stopword` VALUES ('menanya');
INSERT INTO `stopword` VALUES ('menanyai');
INSERT INTO `stopword` VALUES ('menanyakan');
INSERT INTO `stopword` VALUES ('mendapat');
INSERT INTO `stopword` VALUES ('mendapatkan');
INSERT INTO `stopword` VALUES ('mendatang');
INSERT INTO `stopword` VALUES ('mendatangi');
INSERT INTO `stopword` VALUES ('mendatangkan');
INSERT INTO `stopword` VALUES ('menegaskan');
INSERT INTO `stopword` VALUES ('mengakhiri');
INSERT INTO `stopword` VALUES ('mengapa');
INSERT INTO `stopword` VALUES ('mengatakan');
INSERT INTO `stopword` VALUES ('mengatakannya');
INSERT INTO `stopword` VALUES ('mengenai');
INSERT INTO `stopword` VALUES ('mengerjakan');
INSERT INTO `stopword` VALUES ('mengetahui');
INSERT INTO `stopword` VALUES ('menggunakan');
INSERT INTO `stopword` VALUES ('menghendaki');
INSERT INTO `stopword` VALUES ('mengibaratkan');
INSERT INTO `stopword` VALUES ('mengibaratkannya');
INSERT INTO `stopword` VALUES ('mengingat');
INSERT INTO `stopword` VALUES ('mengingatkan');
INSERT INTO `stopword` VALUES ('menginginkan');
INSERT INTO `stopword` VALUES ('mengira');
INSERT INTO `stopword` VALUES ('mengucapkan');
INSERT INTO `stopword` VALUES ('mengucapkannya');
INSERT INTO `stopword` VALUES ('mengungkapkan');
INSERT INTO `stopword` VALUES ('menjadi');
INSERT INTO `stopword` VALUES ('menjawab');
INSERT INTO `stopword` VALUES ('menjelaskan');
INSERT INTO `stopword` VALUES ('menuju');
INSERT INTO `stopword` VALUES ('menunjuk');
INSERT INTO `stopword` VALUES ('menunjuki');
INSERT INTO `stopword` VALUES ('menunjukkan');
INSERT INTO `stopword` VALUES ('menunjuknya');
INSERT INTO `stopword` VALUES ('menurut');
INSERT INTO `stopword` VALUES ('menuturkan');
INSERT INTO `stopword` VALUES ('menyampaikan');
INSERT INTO `stopword` VALUES ('menyangkut');
INSERT INTO `stopword` VALUES ('menyatakan');
INSERT INTO `stopword` VALUES ('menyebutkan');
INSERT INTO `stopword` VALUES ('menyeluruh');
INSERT INTO `stopword` VALUES ('menyiapkan');
INSERT INTO `stopword` VALUES ('merasa');
INSERT INTO `stopword` VALUES ('mereka');
INSERT INTO `stopword` VALUES ('merekalah');
INSERT INTO `stopword` VALUES ('merupakan');
INSERT INTO `stopword` VALUES ('meski');
INSERT INTO `stopword` VALUES ('meskipun');
INSERT INTO `stopword` VALUES ('meyakini');
INSERT INTO `stopword` VALUES ('meyakinkan');
INSERT INTO `stopword` VALUES ('minta');
INSERT INTO `stopword` VALUES ('mirip');
INSERT INTO `stopword` VALUES ('misal');
INSERT INTO `stopword` VALUES ('misalkan');
INSERT INTO `stopword` VALUES ('misalnya');
INSERT INTO `stopword` VALUES ('mula');
INSERT INTO `stopword` VALUES ('mulai');
INSERT INTO `stopword` VALUES ('mulailah');
INSERT INTO `stopword` VALUES ('mulanya');
INSERT INTO `stopword` VALUES ('mungkin');
INSERT INTO `stopword` VALUES ('mungkinkah');
INSERT INTO `stopword` VALUES ('nah');
INSERT INTO `stopword` VALUES ('naik');
INSERT INTO `stopword` VALUES ('namun');
INSERT INTO `stopword` VALUES ('nanti');
INSERT INTO `stopword` VALUES ('nantinya');
INSERT INTO `stopword` VALUES ('nyaris');
INSERT INTO `stopword` VALUES ('nyatanya');
INSERT INTO `stopword` VALUES ('olah');
INSERT INTO `stopword` VALUES ('oleh');
INSERT INTO `stopword` VALUES ('olehnya');
INSERT INTO `stopword` VALUES ('pada');
INSERT INTO `stopword` VALUES ('padahal');
INSERT INTO `stopword` VALUES ('padanya');
INSERT INTO `stopword` VALUES ('pak');
INSERT INTO `stopword` VALUES ('paling');
INSERT INTO `stopword` VALUES ('panjang');
INSERT INTO `stopword` VALUES ('pantas');
INSERT INTO `stopword` VALUES ('para');
INSERT INTO `stopword` VALUES ('pasti');
INSERT INTO `stopword` VALUES ('pastilah');
INSERT INTO `stopword` VALUES ('penting');
INSERT INTO `stopword` VALUES ('pentingnya');
INSERT INTO `stopword` VALUES ('per');
INSERT INTO `stopword` VALUES ('percuma');
INSERT INTO `stopword` VALUES ('perlu');
INSERT INTO `stopword` VALUES ('perlukah');
INSERT INTO `stopword` VALUES ('perlunya');
INSERT INTO `stopword` VALUES ('pernah');
INSERT INTO `stopword` VALUES ('persoalan');
INSERT INTO `stopword` VALUES ('pertama');
INSERT INTO `stopword` VALUES ('pertanyaan');
INSERT INTO `stopword` VALUES ('pertanyakan');
INSERT INTO `stopword` VALUES ('pihak');
INSERT INTO `stopword` VALUES ('pihaknya');
INSERT INTO `stopword` VALUES ('pukul');
INSERT INTO `stopword` VALUES ('pula');
INSERT INTO `stopword` VALUES ('pun');
INSERT INTO `stopword` VALUES ('punya');
INSERT INTO `stopword` VALUES ('rasa');
INSERT INTO `stopword` VALUES ('rasanya');
INSERT INTO `stopword` VALUES ('rata');
INSERT INTO `stopword` VALUES ('rupanya');
INSERT INTO `stopword` VALUES ('saat');
INSERT INTO `stopword` VALUES ('saatnya');
INSERT INTO `stopword` VALUES ('saja');
INSERT INTO `stopword` VALUES ('sajalah');
INSERT INTO `stopword` VALUES ('saling');
INSERT INTO `stopword` VALUES ('sama');
INSERT INTO `stopword` VALUES ('sambil');
INSERT INTO `stopword` VALUES ('sampai');
INSERT INTO `stopword` VALUES ('sampaikan');
INSERT INTO `stopword` VALUES ('sana');
INSERT INTO `stopword` VALUES ('sangat');
INSERT INTO `stopword` VALUES ('sangatlah');
INSERT INTO `stopword` VALUES ('satu');
INSERT INTO `stopword` VALUES ('saya');
INSERT INTO `stopword` VALUES ('sayalah');
INSERT INTO `stopword` VALUES ('se');
INSERT INTO `stopword` VALUES ('sebab');
INSERT INTO `stopword` VALUES ('sebabnya');
INSERT INTO `stopword` VALUES ('sebagai');
INSERT INTO `stopword` VALUES ('sebagaimana');
INSERT INTO `stopword` VALUES ('sebagainya');
INSERT INTO `stopword` VALUES ('sebagian');
INSERT INTO `stopword` VALUES ('sebaik');
INSERT INTO `stopword` VALUES ('sebaiknya');
INSERT INTO `stopword` VALUES ('sebaliknya');
INSERT INTO `stopword` VALUES ('sebanyak');
INSERT INTO `stopword` VALUES ('sebegini');
INSERT INTO `stopword` VALUES ('sebegitu');
INSERT INTO `stopword` VALUES ('sebelum');
INSERT INTO `stopword` VALUES ('sebelumnya');
INSERT INTO `stopword` VALUES ('sebenarnya');
INSERT INTO `stopword` VALUES ('seberapa');
INSERT INTO `stopword` VALUES ('sebesar');
INSERT INTO `stopword` VALUES ('sebetulnya');
INSERT INTO `stopword` VALUES ('sebisanya');
INSERT INTO `stopword` VALUES ('sebuah');
INSERT INTO `stopword` VALUES ('sebut');
INSERT INTO `stopword` VALUES ('sebutlah');
INSERT INTO `stopword` VALUES ('sebutnya');
INSERT INTO `stopword` VALUES ('secara');
INSERT INTO `stopword` VALUES ('secukupnya');
INSERT INTO `stopword` VALUES ('sedang');
INSERT INTO `stopword` VALUES ('sedangkan');
INSERT INTO `stopword` VALUES ('sedemikian');
INSERT INTO `stopword` VALUES ('sedikit');
INSERT INTO `stopword` VALUES ('sedikitnya');
INSERT INTO `stopword` VALUES ('seenaknya');
INSERT INTO `stopword` VALUES ('segala');
INSERT INTO `stopword` VALUES ('segalanya');
INSERT INTO `stopword` VALUES ('segera');
INSERT INTO `stopword` VALUES ('seharusnya');
INSERT INTO `stopword` VALUES ('sehingga');
INSERT INTO `stopword` VALUES ('seingat');
INSERT INTO `stopword` VALUES ('sejak');
INSERT INTO `stopword` VALUES ('sejauh');
INSERT INTO `stopword` VALUES ('sejenak');
INSERT INTO `stopword` VALUES ('sejumlah');
INSERT INTO `stopword` VALUES ('sekadar');
INSERT INTO `stopword` VALUES ('sekadarnya');
INSERT INTO `stopword` VALUES ('sekali');
INSERT INTO `stopword` VALUES ('sekalian');
INSERT INTO `stopword` VALUES ('sekaligus');
INSERT INTO `stopword` VALUES ('sekalipun');
INSERT INTO `stopword` VALUES ('sekarang');
INSERT INTO `stopword` VALUES ('sekecil');
INSERT INTO `stopword` VALUES ('seketika');
INSERT INTO `stopword` VALUES ('sekiranya');
INSERT INTO `stopword` VALUES ('sekitar');
INSERT INTO `stopword` VALUES ('sekitarnya');
INSERT INTO `stopword` VALUES ('sekurang');
INSERT INTO `stopword` VALUES ('sekurangnya');
INSERT INTO `stopword` VALUES ('sela');
INSERT INTO `stopword` VALUES ('selain');
INSERT INTO `stopword` VALUES ('selaku');
INSERT INTO `stopword` VALUES ('selalu');
INSERT INTO `stopword` VALUES ('selama');
INSERT INTO `stopword` VALUES ('selamanya');
INSERT INTO `stopword` VALUES ('selanjutnya');
INSERT INTO `stopword` VALUES ('seluruh');
INSERT INTO `stopword` VALUES ('seluruhnya');
INSERT INTO `stopword` VALUES ('semacam');
INSERT INTO `stopword` VALUES ('semakin');
INSERT INTO `stopword` VALUES ('semampu');
INSERT INTO `stopword` VALUES ('semampunya');
INSERT INTO `stopword` VALUES ('semasa');
INSERT INTO `stopword` VALUES ('semasih');
INSERT INTO `stopword` VALUES ('semata');
INSERT INTO `stopword` VALUES ('semaunya');
INSERT INTO `stopword` VALUES ('sementara');
INSERT INTO `stopword` VALUES ('semisal');
INSERT INTO `stopword` VALUES ('semisalnya');
INSERT INTO `stopword` VALUES ('sempat');
INSERT INTO `stopword` VALUES ('semua');
INSERT INTO `stopword` VALUES ('semuanya');
INSERT INTO `stopword` VALUES ('semula');
INSERT INTO `stopword` VALUES ('sendiri');
INSERT INTO `stopword` VALUES ('sendirian');
INSERT INTO `stopword` VALUES ('sendirinya');
INSERT INTO `stopword` VALUES ('seolah');
INSERT INTO `stopword` VALUES ('seorang');
INSERT INTO `stopword` VALUES ('sepanjang');
INSERT INTO `stopword` VALUES ('sepantasnya');
INSERT INTO `stopword` VALUES ('sepantasnyalah');
INSERT INTO `stopword` VALUES ('seperlunya');
INSERT INTO `stopword` VALUES ('seperti');
INSERT INTO `stopword` VALUES ('sepertinya');
INSERT INTO `stopword` VALUES ('sepihak');
INSERT INTO `stopword` VALUES ('sering');
INSERT INTO `stopword` VALUES ('seringnya');
INSERT INTO `stopword` VALUES ('serta');
INSERT INTO `stopword` VALUES ('serupa');
INSERT INTO `stopword` VALUES ('sesaat');
INSERT INTO `stopword` VALUES ('sesama');
INSERT INTO `stopword` VALUES ('sesampai');
INSERT INTO `stopword` VALUES ('sesegera');
INSERT INTO `stopword` VALUES ('sesekali');
INSERT INTO `stopword` VALUES ('seseorang');
INSERT INTO `stopword` VALUES ('sesuatu');
INSERT INTO `stopword` VALUES ('sesuatunya');
INSERT INTO `stopword` VALUES ('sesudah');
INSERT INTO `stopword` VALUES ('sesudahnya');
INSERT INTO `stopword` VALUES ('setelah');
INSERT INTO `stopword` VALUES ('setempat');
INSERT INTO `stopword` VALUES ('setengah');
INSERT INTO `stopword` VALUES ('seterusnya');
INSERT INTO `stopword` VALUES ('setiap');
INSERT INTO `stopword` VALUES ('setiba');
INSERT INTO `stopword` VALUES ('setibanya');
INSERT INTO `stopword` VALUES ('setidak');
INSERT INTO `stopword` VALUES ('setidaknya');
INSERT INTO `stopword` VALUES ('setinggi');
INSERT INTO `stopword` VALUES ('seusai');
INSERT INTO `stopword` VALUES ('sewaktu');
INSERT INTO `stopword` VALUES ('siap');
INSERT INTO `stopword` VALUES ('siapa');
INSERT INTO `stopword` VALUES ('siapakah');
INSERT INTO `stopword` VALUES ('siapapun');
INSERT INTO `stopword` VALUES ('sini');
INSERT INTO `stopword` VALUES ('sinilah');
INSERT INTO `stopword` VALUES ('soal');
INSERT INTO `stopword` VALUES ('soalnya');
INSERT INTO `stopword` VALUES ('suatu');
INSERT INTO `stopword` VALUES ('sudah');
INSERT INTO `stopword` VALUES ('sudahkah');
INSERT INTO `stopword` VALUES ('sudahlah');
INSERT INTO `stopword` VALUES ('supaya');
INSERT INTO `stopword` VALUES ('tadi');
INSERT INTO `stopword` VALUES ('tadinya');
INSERT INTO `stopword` VALUES ('tahu');
INSERT INTO `stopword` VALUES ('tahun');
INSERT INTO `stopword` VALUES ('tak');
INSERT INTO `stopword` VALUES ('tama');
INSERT INTO `stopword` VALUES ('tambah');
INSERT INTO `stopword` VALUES ('tambahnya');
INSERT INTO `stopword` VALUES ('tampak');
INSERT INTO `stopword` VALUES ('tampaknya');
INSERT INTO `stopword` VALUES ('tandas');
INSERT INTO `stopword` VALUES ('tandasnya');
INSERT INTO `stopword` VALUES ('tanpa');
INSERT INTO `stopword` VALUES ('tanya');
INSERT INTO `stopword` VALUES ('tanyakan');
INSERT INTO `stopword` VALUES ('tanyanya');
INSERT INTO `stopword` VALUES ('tapi');
INSERT INTO `stopword` VALUES ('tegas');
INSERT INTO `stopword` VALUES ('tegasnya');
INSERT INTO `stopword` VALUES ('telah');
INSERT INTO `stopword` VALUES ('tempat');
INSERT INTO `stopword` VALUES ('tengah');
INSERT INTO `stopword` VALUES ('tentang');
INSERT INTO `stopword` VALUES ('tentu');
INSERT INTO `stopword` VALUES ('tentulah');
INSERT INTO `stopword` VALUES ('tentunya');
INSERT INTO `stopword` VALUES ('tepat');
INSERT INTO `stopword` VALUES ('terakhir');
INSERT INTO `stopword` VALUES ('terasa');
INSERT INTO `stopword` VALUES ('terbanyak');
INSERT INTO `stopword` VALUES ('terdahulu');
INSERT INTO `stopword` VALUES ('terdapat');
INSERT INTO `stopword` VALUES ('terdiri');
INSERT INTO `stopword` VALUES ('terhadap');
INSERT INTO `stopword` VALUES ('terhadapnya');
INSERT INTO `stopword` VALUES ('teringat');
INSERT INTO `stopword` VALUES ('terjadi');
INSERT INTO `stopword` VALUES ('terjadilah');
INSERT INTO `stopword` VALUES ('terjadinya');
INSERT INTO `stopword` VALUES ('terkira');
INSERT INTO `stopword` VALUES ('terlalu');
INSERT INTO `stopword` VALUES ('terlebih');
INSERT INTO `stopword` VALUES ('terlihat');
INSERT INTO `stopword` VALUES ('termasuk');
INSERT INTO `stopword` VALUES ('ternyata');
INSERT INTO `stopword` VALUES ('tersampaikan');
INSERT INTO `stopword` VALUES ('tersebut');
INSERT INTO `stopword` VALUES ('tersebutlah');
INSERT INTO `stopword` VALUES ('tertentu');
INSERT INTO `stopword` VALUES ('tertuju');
INSERT INTO `stopword` VALUES ('terus');
INSERT INTO `stopword` VALUES ('terutama');
INSERT INTO `stopword` VALUES ('tetap');
INSERT INTO `stopword` VALUES ('tetapi');
INSERT INTO `stopword` VALUES ('tiap');
INSERT INTO `stopword` VALUES ('tiba');
INSERT INTO `stopword` VALUES ('tidak');
INSERT INTO `stopword` VALUES ('tidakkah');
INSERT INTO `stopword` VALUES ('tidaklah');
INSERT INTO `stopword` VALUES ('tidaknya');
INSERT INTO `stopword` VALUES ('tiga');
INSERT INTO `stopword` VALUES ('tinggi');
INSERT INTO `stopword` VALUES ('toh');
INSERT INTO `stopword` VALUES ('tunjuk');
INSERT INTO `stopword` VALUES ('turut');
INSERT INTO `stopword` VALUES ('tutur');
INSERT INTO `stopword` VALUES ('tuturnya');
INSERT INTO `stopword` VALUES ('ucap');
INSERT INTO `stopword` VALUES ('ucapnya');
INSERT INTO `stopword` VALUES ('ujar');
INSERT INTO `stopword` VALUES ('ujarnya');
INSERT INTO `stopword` VALUES ('umum');
INSERT INTO `stopword` VALUES ('umumnya');
INSERT INTO `stopword` VALUES ('ungkap');
INSERT INTO `stopword` VALUES ('ungkapnya');
INSERT INTO `stopword` VALUES ('untuk');
INSERT INTO `stopword` VALUES ('usah');
INSERT INTO `stopword` VALUES ('usai');
INSERT INTO `stopword` VALUES ('waduh');
INSERT INTO `stopword` VALUES ('wah');
INSERT INTO `stopword` VALUES ('wahai');
INSERT INTO `stopword` VALUES ('waktu');
INSERT INTO `stopword` VALUES ('waktunya');
INSERT INTO `stopword` VALUES ('walau');
INSERT INTO `stopword` VALUES ('walaupun');
INSERT INTO `stopword` VALUES ('wong');
INSERT INTO `stopword` VALUES ('yaitu');
INSERT INTO `stopword` VALUES ('yakin');
INSERT INTO `stopword` VALUES ('yakni');
INSERT INTO `stopword` VALUES ('yang');

-- ----------------------------
-- Table structure for token
-- ----------------------------
DROP TABLE IF EXISTS `token`;
CREATE TABLE `token`  (
  `id` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `no` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kode` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kata` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `freq` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  INDEX `no`(`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of token
-- ----------------------------
INSERT INTO `token` VALUES ('1', '1', '0', 'bantuan', '1');
INSERT INTO `token` VALUES ('1', '2', '0', 'langsung', '1');
INSERT INTO `token` VALUES ('1', '3', '0', 'tunai', '1');
INSERT INTO `token` VALUES ('1', '4', '0', 'blt', '1');
INSERT INTO `token` VALUES ('1', '5', '0', 'airlangga', '1');
INSERT INTO `token` VALUES ('1', '6', '0', 'hartanto', '1');
INSERT INTO `token` VALUES ('', '', '0', 'roda', '1');
INSERT INTO `token` VALUES ('', '', '0', 'serasa', '1');
INSERT INTO `token` VALUES ('', '', '0', 'rodakursi', '1');
INSERT INTO `token` VALUES ('', '', '0', 'roda', '1');
INSERT INTO `token` VALUES ('', '', '0', 'murahmeriah', '1');
INSERT INTO `token` VALUES ('', '', '0', 'surabaya', '1');
INSERT INTO `token` VALUES ('', '', '0', 'ootd', '1');
INSERT INTO `token` VALUES ('2', '1', '0', '', '1');
INSERT INTO `token` VALUES ('2', '2', '0', '', '1');
INSERT INTO `token` VALUES ('2', '3', '0', '', '1');
INSERT INTO `token` VALUES ('2', '4', '0', '', '1');
INSERT INTO `token` VALUES ('2', '5', '0', '', '1');
INSERT INTO `token` VALUES ('2', '6', '0', '', '1');
INSERT INTO `token` VALUES ('2', '7', '0', '', '1');
INSERT INTO `token` VALUES ('2', '8', '0', '', '1');
INSERT INTO `token` VALUES ('2', '9', '0', '', '1');
INSERT INTO `token` VALUES ('2', '10', '0', '', '1');
INSERT INTO `token` VALUES ('2', '11', '0', '', '1');
INSERT INTO `token` VALUES ('2', '12', '0', '', '1');
INSERT INTO `token` VALUES ('2', '13', '0', '', '1');
INSERT INTO `token` VALUES ('2', '17', '0', '', '1');
INSERT INTO `token` VALUES ('2', '18', '0', '', '1');
INSERT INTO `token` VALUES ('2', '19', '0', '', '1');
INSERT INTO `token` VALUES ('2', '20', '0', '', '1');
INSERT INTO `token` VALUES ('2', '21', '0', '', '1');
INSERT INTO `token` VALUES ('2', '22', '0', '', '1');
INSERT INTO `token` VALUES ('2', '26', '0', '', '1');
INSERT INTO `token` VALUES ('3', '1', '0', '', '1');
INSERT INTO `token` VALUES ('3', '2', '0', '', '1');
INSERT INTO `token` VALUES ('3', '4', '0', '', '1');
INSERT INTO `token` VALUES ('3', '6', '0', '', '1');
INSERT INTO `token` VALUES ('3', '7', '0', '', '1');
INSERT INTO `token` VALUES ('3', '8', '0', '', '1');
INSERT INTO `token` VALUES ('3', '10', '0', '', '1');
INSERT INTO `token` VALUES ('3', '14', '0', '', '1');
INSERT INTO `token` VALUES ('3', '16', '0', '', '1');
INSERT INTO `token` VALUES ('3', '18', '0', '', '1');
INSERT INTO `token` VALUES ('3', '19', '0', '', '1');
INSERT INTO `token` VALUES ('3', '21', '0', '', '1');
INSERT INTO `token` VALUES ('3', '22', '0', '', '1');
INSERT INTO `token` VALUES ('3', '23', '0', '', '1');
INSERT INTO `token` VALUES ('3', '24', '0', '', '1');
INSERT INTO `token` VALUES ('3', '25', '0', '', '1');
INSERT INTO `token` VALUES ('4', '1', '0', '', '1');
INSERT INTO `token` VALUES ('4', '2', '0', '', '1');
INSERT INTO `token` VALUES ('4', '3', '0', '', '1');
INSERT INTO `token` VALUES ('4', '6', '0', '', '1');
INSERT INTO `token` VALUES ('4', '7', '0', '', '1');
INSERT INTO `token` VALUES ('4', '13', '0', '', '1');
INSERT INTO `token` VALUES ('4', '14', '0', '', '1');
INSERT INTO `token` VALUES ('4', '15', '0', '', '1');
INSERT INTO `token` VALUES ('4', '16', '0', '', '1');
INSERT INTO `token` VALUES ('4', '17', '0', '', '1');
INSERT INTO `token` VALUES ('4', '19', '0', '', '1');
INSERT INTO `token` VALUES ('5', '1', '0', '', '1');
INSERT INTO `token` VALUES ('5', '2', '0', '', '1');
INSERT INTO `token` VALUES ('5', '3', '0', '', '1');
INSERT INTO `token` VALUES ('5', '5', '0', '', '1');
INSERT INTO `token` VALUES ('5', '6', '0', '', '1');
INSERT INTO `token` VALUES ('5', '8', '0', '', '1');
INSERT INTO `token` VALUES ('5', '9', '0', '', '1');
INSERT INTO `token` VALUES ('5', '12', '0', '', '1');
INSERT INTO `token` VALUES ('5', '14', '0', '', '1');
INSERT INTO `token` VALUES ('5', '17', '0', '', '1');
INSERT INTO `token` VALUES ('5', '18', '0', '', '1');
INSERT INTO `token` VALUES ('5', '19', '0', '', '1');
INSERT INTO `token` VALUES ('5', '20', '0', '', '1');
INSERT INTO `token` VALUES ('5', '23', '0', '', '1');
INSERT INTO `token` VALUES ('6', '1', '0', '', '1');
INSERT INTO `token` VALUES ('6', '2', '0', '', '1');
INSERT INTO `token` VALUES ('6', '3', '0', '', '1');
INSERT INTO `token` VALUES ('6', '4', '0', '', '1');
INSERT INTO `token` VALUES ('6', '5', '0', '', '1');
INSERT INTO `token` VALUES ('6', '6', '0', '', '1');
INSERT INTO `token` VALUES ('6', '7', '0', '', '1');
INSERT INTO `token` VALUES ('6', '8', '0', '', '1');
INSERT INTO `token` VALUES ('6', '9', '0', '', '1');
INSERT INTO `token` VALUES ('6', '10', '0', '', '1');
INSERT INTO `token` VALUES ('6', '11', '0', '', '1');
INSERT INTO `token` VALUES ('6', '12', '0', '', '1');
INSERT INTO `token` VALUES ('6', '13', '0', '', '1');
INSERT INTO `token` VALUES ('6', '14', '0', '', '1');
INSERT INTO `token` VALUES ('6', '15', '0', '', '1');
INSERT INTO `token` VALUES ('6', '16', '0', '', '1');
INSERT INTO `token` VALUES ('6', '18', '0', '', '1');
INSERT INTO `token` VALUES ('6', '19', '0', '', '1');
INSERT INTO `token` VALUES ('6', '20', '0', '', '1');
INSERT INTO `token` VALUES ('6', '21', '0', '', '1');
INSERT INTO `token` VALUES ('7', '1', '0', '', '1');
INSERT INTO `token` VALUES ('7', '2', '0', '', '1');
INSERT INTO `token` VALUES ('7', '3', '0', '', '1');
INSERT INTO `token` VALUES ('7', '4', '0', '', '1');
INSERT INTO `token` VALUES ('7', '5', '0', '', '1');
INSERT INTO `token` VALUES ('7', '7', '0', '', '1');
INSERT INTO `token` VALUES ('7', '8', '0', '', '1');
INSERT INTO `token` VALUES ('7', '10', '0', '', '1');
INSERT INTO `token` VALUES ('7', '11', '0', '', '1');
INSERT INTO `token` VALUES ('7', '13', '0', '', '1');
INSERT INTO `token` VALUES ('7', '14', '0', '', '1');
INSERT INTO `token` VALUES ('7', '15', '0', '', '1');
INSERT INTO `token` VALUES ('7', '16', '0', '', '1');
INSERT INTO `token` VALUES ('7', '17', '0', '', '1');
INSERT INTO `token` VALUES ('7', '18', '0', '', '1');
INSERT INTO `token` VALUES ('7', '19', '0', '', '1');
INSERT INTO `token` VALUES ('7', '20', '0', '', '1');
INSERT INTO `token` VALUES ('7', '21', '0', '', '1');
INSERT INTO `token` VALUES ('7', '22', '0', '', '1');
INSERT INTO `token` VALUES ('7', '23', '0', '', '1');
INSERT INTO `token` VALUES ('8', '1', '0', '', '1');
INSERT INTO `token` VALUES ('8', '2', '0', '', '1');
INSERT INTO `token` VALUES ('8', '3', '0', '', '1');
INSERT INTO `token` VALUES ('8', '4', '0', '', '1');
INSERT INTO `token` VALUES ('8', '5', '0', '', '1');
INSERT INTO `token` VALUES ('8', '6', '0', '', '1');
INSERT INTO `token` VALUES ('8', '7', '0', '', '1');
INSERT INTO `token` VALUES ('8', '8', '0', '', '1');
INSERT INTO `token` VALUES ('8', '9', '0', '', '1');
INSERT INTO `token` VALUES ('8', '10', '0', '', '1');
INSERT INTO `token` VALUES ('8', '11', '0', '', '1');
INSERT INTO `token` VALUES ('8', '12', '0', '', '1');
INSERT INTO `token` VALUES ('8', '13', '0', '', '1');
INSERT INTO `token` VALUES ('8', '14', '0', '', '1');
INSERT INTO `token` VALUES ('8', '15', '0', '', '1');
INSERT INTO `token` VALUES ('8', '16', '0', '', '1');
INSERT INTO `token` VALUES ('8', '17', '0', '', '1');
INSERT INTO `token` VALUES ('8', '18', '0', '', '1');
INSERT INTO `token` VALUES ('8', '19', '0', '', '1');
INSERT INTO `token` VALUES ('8', '20', '0', '', '1');
INSERT INTO `token` VALUES ('8', '21', '0', '', '1');
INSERT INTO `token` VALUES ('8', '22', '0', '', '1');
INSERT INTO `token` VALUES ('8', '23', '0', '', '1');
INSERT INTO `token` VALUES ('8', '24', '0', '', '1');
INSERT INTO `token` VALUES ('8', '25', '0', '', '1');
INSERT INTO `token` VALUES ('8', '26', '0', '', '1');
INSERT INTO `token` VALUES ('9', '3', '0', '', '1');
INSERT INTO `token` VALUES ('9', '6', '0', '', '1');
INSERT INTO `token` VALUES ('9', '7', '0', '', '1');
INSERT INTO `token` VALUES ('9', '8', '0', '', '1');
INSERT INTO `token` VALUES ('9', '9', '0', '', '1');
INSERT INTO `token` VALUES ('9', '18', '0', '', '1');
INSERT INTO `token` VALUES ('9', '19', '0', '', '1');
INSERT INTO `token` VALUES ('9', '20', '0', '', '1');
INSERT INTO `token` VALUES ('9', '22', '0', '', '1');
INSERT INTO `token` VALUES ('9', '23', '0', '', '1');
INSERT INTO `token` VALUES ('10', '1', '0', '', '1');
INSERT INTO `token` VALUES ('10', '2', '0', '', '1');
INSERT INTO `token` VALUES ('10', '3', '0', '', '1');
INSERT INTO `token` VALUES ('10', '4', '0', '', '1');
INSERT INTO `token` VALUES ('10', '5', '0', '', '1');
INSERT INTO `token` VALUES ('10', '6', '0', '', '1');
INSERT INTO `token` VALUES ('10', '7', '0', '', '1');
INSERT INTO `token` VALUES ('10', '8', '0', '', '1');
INSERT INTO `token` VALUES ('10', '10', '0', '', '1');
INSERT INTO `token` VALUES ('10', '12', '0', '', '1');
INSERT INTO `token` VALUES ('10', '14', '0', '', '1');
INSERT INTO `token` VALUES ('10', '15', '0', '', '1');
INSERT INTO `token` VALUES ('10', '16', '0', '', '1');
INSERT INTO `token` VALUES ('10', '17', '0', '', '1');
INSERT INTO `token` VALUES ('10', '18', '0', '', '1');
INSERT INTO `token` VALUES ('10', '21', '0', '', '1');
INSERT INTO `token` VALUES ('10', '24', '0', '', '1');
INSERT INTO `token` VALUES ('11', '1', '0', '', '1');
INSERT INTO `token` VALUES ('11', '2', '0', '', '1');
INSERT INTO `token` VALUES ('11', '3', '0', '', '1');
INSERT INTO `token` VALUES ('11', '4', '0', '', '1');
INSERT INTO `token` VALUES ('11', '5', '0', '', '1');
INSERT INTO `token` VALUES ('11', '7', '0', '', '1');
INSERT INTO `token` VALUES ('11', '8', '0', '', '1');
INSERT INTO `token` VALUES ('11', '10', '0', '', '1');
INSERT INTO `token` VALUES ('11', '11', '0', '', '1');
INSERT INTO `token` VALUES ('11', '12', '0', '', '1');
INSERT INTO `token` VALUES ('11', '14', '0', '', '1');
INSERT INTO `token` VALUES ('11', '15', '0', '', '1');
INSERT INTO `token` VALUES ('11', '16', '0', '', '1');
INSERT INTO `token` VALUES ('11', '17', '0', '', '1');
INSERT INTO `token` VALUES ('11', '18', '0', '', '1');
INSERT INTO `token` VALUES ('11', '20', '0', '', '1');
INSERT INTO `token` VALUES ('12', '1', '0', '', '1');
INSERT INTO `token` VALUES ('12', '2', '0', '', '1');
INSERT INTO `token` VALUES ('12', '3', '0', '', '1');
INSERT INTO `token` VALUES ('12', '4', '0', '', '1');
INSERT INTO `token` VALUES ('12', '5', '0', '', '1');
INSERT INTO `token` VALUES ('12', '6', '0', '', '1');
INSERT INTO `token` VALUES ('12', '8', '0', '', '1');
INSERT INTO `token` VALUES ('12', '9', '0', '', '1');
INSERT INTO `token` VALUES ('12', '10', '0', '', '1');
INSERT INTO `token` VALUES ('12', '12', '0', '', '1');
INSERT INTO `token` VALUES ('12', '13', '0', '', '1');
INSERT INTO `token` VALUES ('12', '14', '0', '', '1');
INSERT INTO `token` VALUES ('12', '15', '0', '', '1');
INSERT INTO `token` VALUES ('12', '16', '0', '', '1');
INSERT INTO `token` VALUES ('12', '18', '0', '', '1');
INSERT INTO `token` VALUES ('13', '3', '0', '', '1');
INSERT INTO `token` VALUES ('13', '4', '0', '', '1');
INSERT INTO `token` VALUES ('13', '5', '0', '', '1');
INSERT INTO `token` VALUES ('13', '9', '0', '', '1');
INSERT INTO `token` VALUES ('13', '11', '0', '', '1');
INSERT INTO `token` VALUES ('13', '14', '0', '', '1');
INSERT INTO `token` VALUES ('13', '16', '0', '', '1');
INSERT INTO `token` VALUES ('13', '17', '0', '', '1');
INSERT INTO `token` VALUES ('13', '18', '0', '', '1');
INSERT INTO `token` VALUES ('13', '19', '0', '', '1');
INSERT INTO `token` VALUES ('13', '20', '0', '', '1');
INSERT INTO `token` VALUES ('13', '21', '0', '', '1');
INSERT INTO `token` VALUES ('13', '22', '0', '', '1');
INSERT INTO `token` VALUES ('13', '23', '0', '', '1');
INSERT INTO `token` VALUES ('13', '24', '0', '', '1');
INSERT INTO `token` VALUES ('13', '25', '0', '', '1');
INSERT INTO `token` VALUES ('13', '26', '0', '', '1');
INSERT INTO `token` VALUES ('13', '27', '0', '', '1');
INSERT INTO `token` VALUES ('14', '1', '0', '', '1');
INSERT INTO `token` VALUES ('14', '2', '0', '', '1');
INSERT INTO `token` VALUES ('14', '3', '0', '', '1');
INSERT INTO `token` VALUES ('14', '4', '0', '', '1');
INSERT INTO `token` VALUES ('14', '5', '0', '', '1');
INSERT INTO `token` VALUES ('14', '6', '0', '', '1');
INSERT INTO `token` VALUES ('14', '7', '0', '', '1');
INSERT INTO `token` VALUES ('14', '8', '0', '', '1');
INSERT INTO `token` VALUES ('14', '9', '0', '', '1');
INSERT INTO `token` VALUES ('14', '11', '0', '', '1');
INSERT INTO `token` VALUES ('14', '12', '0', '', '1');
INSERT INTO `token` VALUES ('14', '13', '0', '', '1');
INSERT INTO `token` VALUES ('14', '15', '0', '', '1');
INSERT INTO `token` VALUES ('14', '16', '0', '', '1');
INSERT INTO `token` VALUES ('14', '17', '0', '', '1');
INSERT INTO `token` VALUES ('14', '18', '0', '', '1');
INSERT INTO `token` VALUES ('14', '19', '0', '', '1');
INSERT INTO `token` VALUES ('14', '20', '0', '', '1');
INSERT INTO `token` VALUES ('14', '21', '0', '', '1');
INSERT INTO `token` VALUES ('15', '1', '0', '', '1');
INSERT INTO `token` VALUES ('15', '2', '0', '', '1');
INSERT INTO `token` VALUES ('15', '3', '0', '', '1');
INSERT INTO `token` VALUES ('15', '4', '0', '', '1');
INSERT INTO `token` VALUES ('15', '6', '0', '', '1');
INSERT INTO `token` VALUES ('15', '7', '0', '', '1');
INSERT INTO `token` VALUES ('15', '9', '0', '', '1');
INSERT INTO `token` VALUES ('15', '10', '0', '', '1');
INSERT INTO `token` VALUES ('15', '11', '0', '', '1');
INSERT INTO `token` VALUES ('15', '12', '0', '', '1');
INSERT INTO `token` VALUES ('15', '13', '0', '', '1');
INSERT INTO `token` VALUES ('15', '15', '0', '', '1');
INSERT INTO `token` VALUES ('15', '16', '0', '', '1');
INSERT INTO `token` VALUES ('15', '18', '0', '', '1');
INSERT INTO `token` VALUES ('15', '19', '0', '', '1');
INSERT INTO `token` VALUES ('16', '2', '0', '', '1');
INSERT INTO `token` VALUES ('16', '3', '0', '', '1');
INSERT INTO `token` VALUES ('16', '4', '0', '', '1');
INSERT INTO `token` VALUES ('16', '6', '0', '', '1');
INSERT INTO `token` VALUES ('16', '8', '0', '', '1');
INSERT INTO `token` VALUES ('16', '9', '0', '', '1');
INSERT INTO `token` VALUES ('16', '10', '0', '', '1');
INSERT INTO `token` VALUES ('16', '11', '0', '', '1');
INSERT INTO `token` VALUES ('16', '13', '0', '', '1');
INSERT INTO `token` VALUES ('16', '15', '0', '', '1');
INSERT INTO `token` VALUES ('16', '17', '0', '', '1');
INSERT INTO `token` VALUES ('16', '18', '0', '', '1');
INSERT INTO `token` VALUES ('16', '19', '0', '', '1');
INSERT INTO `token` VALUES ('16', '20', '0', '', '1');
INSERT INTO `token` VALUES ('16', '21', '0', '', '1');
INSERT INTO `token` VALUES ('16', '22', '0', '', '1');
INSERT INTO `token` VALUES ('16', '23', '0', '', '1');
INSERT INTO `token` VALUES ('16', '24', '0', '', '1');
INSERT INTO `token` VALUES ('17', '1', '0', '', '1');
INSERT INTO `token` VALUES ('17', '2', '0', '', '1');
INSERT INTO `token` VALUES ('17', '3', '0', '', '1');
INSERT INTO `token` VALUES ('17', '4', '0', '', '1');
INSERT INTO `token` VALUES ('17', '5', '0', '', '1');
INSERT INTO `token` VALUES ('17', '6', '0', '', '1');
INSERT INTO `token` VALUES ('17', '7', '0', '', '1');
INSERT INTO `token` VALUES ('17', '8', '0', '', '1');
INSERT INTO `token` VALUES ('17', '9', '0', '', '1');
INSERT INTO `token` VALUES ('17', '10', '0', '', '1');
INSERT INTO `token` VALUES ('17', '12', '0', '', '1');
INSERT INTO `token` VALUES ('17', '13', '0', '', '1');
INSERT INTO `token` VALUES ('17', '14', '0', '', '1');
INSERT INTO `token` VALUES ('17', '15', '0', '', '1');
INSERT INTO `token` VALUES ('17', '16', '0', '', '1');
INSERT INTO `token` VALUES ('17', '17', '0', '', '1');
INSERT INTO `token` VALUES ('17', '18', '0', '', '1');
INSERT INTO `token` VALUES ('17', '19', '0', '', '1');
INSERT INTO `token` VALUES ('18', '1', '0', '', '1');
INSERT INTO `token` VALUES ('18', '2', '0', '', '1');
INSERT INTO `token` VALUES ('18', '3', '0', '', '1');
INSERT INTO `token` VALUES ('18', '4', '0', '', '1');
INSERT INTO `token` VALUES ('18', '5', '0', '', '1');
INSERT INTO `token` VALUES ('18', '6', '0', '', '1');
INSERT INTO `token` VALUES ('18', '7', '0', '', '1');
INSERT INTO `token` VALUES ('18', '8', '0', '', '1');
INSERT INTO `token` VALUES ('18', '9', '0', '', '1');
INSERT INTO `token` VALUES ('18', '10', '0', '', '1');
INSERT INTO `token` VALUES ('18', '15', '0', '', '1');
INSERT INTO `token` VALUES ('18', '16', '0', '', '1');
INSERT INTO `token` VALUES ('18', '17', '0', '', '1');
INSERT INTO `token` VALUES ('18', '18', '0', '', '1');
INSERT INTO `token` VALUES ('18', '19', '0', '', '1');
INSERT INTO `token` VALUES ('18', '20', '0', '', '1');
INSERT INTO `token` VALUES ('18', '21', '0', '', '1');
INSERT INTO `token` VALUES ('18', '22', '0', '', '1');
INSERT INTO `token` VALUES ('19', '1', '0', '', '1');
INSERT INTO `token` VALUES ('19', '2', '0', '', '1');
INSERT INTO `token` VALUES ('19', '4', '0', '', '1');
INSERT INTO `token` VALUES ('19', '5', '0', '', '1');
INSERT INTO `token` VALUES ('19', '9', '0', '', '1');
INSERT INTO `token` VALUES ('19', '11', '0', '', '1');
INSERT INTO `token` VALUES ('19', '12', '0', '', '1');
INSERT INTO `token` VALUES ('19', '13', '0', '', '1');
INSERT INTO `token` VALUES ('19', '15', '0', '', '1');
INSERT INTO `token` VALUES ('19', '17', '0', '', '1');
INSERT INTO `token` VALUES ('19', '19', '0', '', '1');
INSERT INTO `token` VALUES ('19', '20', '0', '', '1');
INSERT INTO `token` VALUES ('20', '1', '0', '', '1');
INSERT INTO `token` VALUES ('20', '2', '0', '', '1');
INSERT INTO `token` VALUES ('20', '3', '0', '', '1');
INSERT INTO `token` VALUES ('20', '5', '0', '', '1');
INSERT INTO `token` VALUES ('20', '6', '0', '', '1');
INSERT INTO `token` VALUES ('20', '7', '0', '', '1');
INSERT INTO `token` VALUES ('20', '10', '0', '', '1');
INSERT INTO `token` VALUES ('20', '11', '0', '', '1');
INSERT INTO `token` VALUES ('20', '12', '0', '', '1');
INSERT INTO `token` VALUES ('20', '13', '0', '', '1');
INSERT INTO `token` VALUES ('20', '14', '0', '', '1');
INSERT INTO `token` VALUES ('20', '15', '0', '', '1');
INSERT INTO `token` VALUES ('20', '16', '0', '', '1');
INSERT INTO `token` VALUES ('20', '17', '0', '', '1');
INSERT INTO `token` VALUES ('20', '18', '0', '', '1');
INSERT INTO `token` VALUES ('20', '20', '0', '', '1');
INSERT INTO `token` VALUES ('20', '22', '0', '', '1');
INSERT INTO `token` VALUES ('20', '23', '0', '', '1');
INSERT INTO `token` VALUES ('20', '25', '0', '', '1');

SET FOREIGN_KEY_CHECKS = 1;
